data:
    # dataset: "mmPoseNLP"
    # dataset: "MMFi"
    # dataset_root: "../mmfi/MMFi_dataset/MMFi_Dataset/Unzipfiles"
    dataset: "MMBody"
    dataset_root: "../mmBody"
    num_joints: 17
    radar_input_c: 5
    train_noise_level: [0.05, 0.1, 0.2]
    test_noise_level: 0.3

train: 
    batch_size: 16
    n_epochs: 100
    learning_rate: 0.0001
    weight_decay: 0.00000001
    gradient_clipping: 1.0
    test_freq: 5
    amp: False

model:
    model: "PointTransformer"
    checkpoint_root_dir: "stream_oracle_checkpoints"

strategy:
    method: "KMeansSampling"
    select_ratio: 0.5
    select_freq: 5
    